ONG/ONG/urls.py
from django.conf.urls import url
from django.contrib import admin


from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('polls.urls')), 
]

ONG/polls/urls.py
from django.conf.urls import url, include

from . import views
from rest_framework import routers

app_name = "polls"

router = routers.DefaultRouter()
router.register(r'Animal', views.AnimalViewSet)
router.register(r'Veterinario', views.VetViewSet)
router.register(r'Doacoes', views.DoacaoViewSet)

urlpatterns = [
    #Viewsets
    url(r'^$', views.index, name='index'),
    url(r'^animal$', views.Animais, name='Animais'),
    url(r'^veterinario$', views.Vet, name='Vet'),
    url(r'^doacao$', views.Doacao, name='Doacoes'),

    ############ Animais
    #cadastro
    url(r'^cadastro_animal$', views.Cadastro_animal, name="cadastro_animal"),
    url(r'^salva_animal', views.Salva_animal, name="Salva_animal"),

    #Rest
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^listagem', include(router.urls)),
    

    #Edicao
    url(r'^edicao_animal', views.Edicao_animal, name="edicao_animal"),
    url(r'^update_animal', views.Update_animal, name="update_animal"),
    url(r'form_update_animal', views.form_update_animal, name='form_update_animal'),

    #Remocao
    url(r'^remocao_animal', views.Remocao_animal, name="remocao_animal"),
    url(r'^remove_animal', views.Remove_animal, name="remove_animal"),

    ############ Veterinarios
    #cadastro
    url(r'^cadastro_vet$', views.Cadastro_vet, name="cadastro_vet"),
    url(r'^salva_vet', views.Salva_vet, name="Salva_vet"),

    #Edicao
    url(r'^edicao_vet', views.Edicao_vet, name="edicao_vet"),
    url(r'^update_vet', views.Update_vet, name="update_vet"),
    url(r'form_update_vet', views.form_update_vet, name='form_update_vet'),

    #Remocao
    url(r'^remocao_vet', views.Remocao_vet, name="remocao_vet"),
    url(r'^remove_vet', views.Remove_vet, name="remove_vet"),

    ############ Doacoes
    #cadastro
    url(r'^cadastro_doacao$', views.Cadastro_doacao, name="cadastro_doacao"),
    url(r'^salva_doacao', views.Salva_doacao, name="salva_doacao"),

    #edicao
    url(r'^edicao_doacao', views.Edicao_doacao, name="edicao_doacao"),
    url(r'^update_doacao', views.Update_doacao, name="update_doacao"),
    url(r'form_update_doacao', views.form_update_doacao, name='form_update_doacao'),

    #Remocao
    url(r'^remocao_doacao', views.Remocao_doacao, name="remocao_doacao"),
    url(r'^remove_doacao', views.Remove_doacao, name="remove_doacao"),
    

    ## Usr
    url(r'^usuario', views.login, name="login"),
    url(r'^logout', views.logout, name="logout"),
]

ONG/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
import datetime
from django.utils import timezone

class Animal(models.Model):
    nome_animal = models.CharField('Nome do Animal', max_length=100)
    idade = models.IntegerField(default= 0)
    especie = models.CharField('Espécie', max_length=100)
    raca = models.CharField('Raça', max_length=100)
    observacao = models.CharField('Observação', max_length=300, blank=True)  # como faz pra n ser NOT NULL??-------------
    #img = models.ImageField(upload_to='Images', blank=True)

    def __str__(self):  #retorna pq é uma chave primaria? Mas ja tem o ID q n repete.....
        return self.nome_animal


class Veterinario(models.Model):
    nome_vet = models.CharField('Nome', max_length=100)
    telefone = models.CharField('Telefone', max_length=30)
    crv = models.CharField('CRV', max_length=30)
    endereco = models.CharField('Endereço', max_length=200)

    def __str__(self):
        return self.nome_vet

class Historico_atendimento(models.Model):
    data_consulta = models.DateTimeField('Data da Consulta')

    animal = models.ForeignKey(Animal, on_delete=models.CASCADE, verbose_name='animal')  # se animal for apagado a FK tbm vai ser
    veterinario = models.ForeignKey(Veterinario, on_delete=models.CASCADE, verbose_name='veterinário')
    observacao = models.CharField('Observação', max_length=300, blank=True) 

    def __str__(self):
        return self.animal
        

  
class Doacoes(models.Model):
    nome_doador = models.CharField('Nome do Doador', max_length=100)
    tel_doador = models.CharField('Telefone do Doador', max_length=100)

     #N aceita PK blank  :/
    #nome_animal = models.ForeignKey(Animal, on_delete=models.CASCADE, default=None, verbose_name='animal') 

    CHOICE = ((u'racao', u'Ração'), (u'med', u'Medicamentos'),)
    tipo_doacao = models.CharField('Tipo de Doação', max_length=15, choices=CHOICE)
    qntidade = models.IntegerField(default=1)

    def __str__(self):
        return self.nome_doador
   

ONG/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import *

from django.shortcuts import get_object_or_404

from .serializers import AnimalSerializer, VetSerializer, DoacoesSerializer

from rest_framework import viewsets

from django.conf import settings


# Create your views here.
def index(request):
    #Pagina principal
    return render(request, 'polls/index.html')

def Animais(request):
    #Pagina de Animais
    return render(request, 'polls/animal.html')

def Vet(request):
    #Pagina de Veterinarios
    return render(request, 'polls/veterinario.html')

def Doacao(request):
    #Pagina de Doacoes
    return render(request, 'polls/doacoes.html')

#### Classes pro Rest-Framework
class AnimalViewSet(viewsets.ModelViewSet):
    queryset = Animal.objects.all() # vai mostrar toda essa tabela
    serializer_class = AnimalSerializer

class VetViewSet(viewsets.ModelViewSet):
    queryset = Veterinario.objects.all()
    serializer_class = VetSerializer

class DoacaoViewSet(viewsets.ModelViewSet):
    queryset = Doacoes.objects.all()
    serializer_class = DoacoesSerializer



##################################################### Usr
def login(request):
    #Verifica se usuario e senha do POST confere com o usuario e senha de settings.py
    
    usr   = settings.DATABASES['default']['USER']
    senha = settings.DATABASES['default']['PASSWORD']

    if usr == request.POST['usuario'] and senha == request.POST['senha']:
            request.session['user_id'] = usr
            return render(request, 'polls/index.html', {'permissao': permissao(request)})
    else:
        return HttpResponse("Usuário e senha não conferem<br/><a href='../'>Voltar</a>")

def permissao(request):
    #Verifica se a sessao do usuario está ativa
    if request.session['user_id'] == settings.DATABASES['default']['USER']:
        print "permi"
        return True
    else: return False

def logout(request):
    #Exclui o usuario de user_id

    if request.session['user_id'] == settings.DATABASES['default']['USER']:
        request.session['user_id'] = None
        return render(request, 'polls/index.html')
    else:
        return HttpResponse("Você não fez login.<a href='../'>Fazer login</a>")  ###ainda n ta bom



#####################################################  Animal

def Cadastro_animal(request):
    #Chama a pagina de cadastro
    if permissao(request):
        return render(request, 'polls/cadastro_animal.html', {'permissao': permissao(request)})
    else:
        return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")
    
     
def Salva_animal(request):
    #Salva os dados no DB
        if request.method == "POST":
            nome = request.POST.get('nome', '')
            idade = request.POST.get('idade', '')
            especie = request.POST.get('especie', '')
            raca = request.POST.get('raca', '')
            obs = request.POST.get('observacao', '')
            animal_obj = Animal(nome_animal=nome, idade=idade,
                especie=especie, raca=raca, observacao=obs)
            animal_obj.save()
            return HttpResponse("Animal cadastrado com sucesso<br/><a href='animal'>Voltar</a>")
            
       

def Edicao_animal(request):
    #chama a pag html com o form pra escolher qual animal editar
    if permissao(request):
        return render(request, 'polls/edicao_animal.html',  
        {"animal": Animal.objects.all(), "permissao": permissao(request)})  #primeiro eu tenho q saber q animal editar
    else: 
        return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")

def form_update_animal(request):
    #chama o html para a edicao de um animal especifico
    selected = str(request.POST.get('animal_selected', ''))
    print type(selected)
    animal = Animal.objects.get(pk=selected)
    return render(request, 'polls/form_update_animal.html',  
    {'animal': animal, "vet": Veterinario.objects.all()})

def Update_animal(request):
    #atualiza o DB
    selected = str(request.POST.get('animal_selected', ''))
    animal = Animal.objects.get(pk=selected)
    nome = request.POST.get('nome', '')
    idade = request.POST.get('idade', '')
    especie = request.POST.get('especie', '')
    raca = request.POST.get('raca', '')
    obs = request.POST.get('observacao', '')
    animal_obj = Animal(pk=selected,nome_animal=nome, idade=idade,      # IDADE N FUNCIONA :/
                especie=especie, raca=raca, observacao=obs)
    animal_obj.save()

    try:
        #pro caso de a edicao for só pro animal e n pra consulta
        consulta     = request.POST.get('data', '')
        vet          = request.POST.get('vet_selected', '')
        obs_consulta = request.POST.get('obs', '')

        vet = Veterinario(pk=vet)           # Instancia de Vet :p
        hist_obj = Historico_atendimento(data_consulta=consulta, animal= animal, 
        veterinario=vet, observacao=obs_consulta)

        hist_obj.save()
    except:
        pass
    return HttpResponse("Animal editado com sucesso<br/><a href='animal'>Voltar</a>")
    


def Remocao_animal(request):
    #Primeiro eu tenho q saber q animal remover
    if permissao(request):
        return render(request, 'polls/remocao_animal.html',
      {"animal": Animal.objects.all(), "permissao": permissao(request)})  
    else: 
        return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")

def Remove_animal(request):
    #atualiza o DB
    selected = str(request.POST.get('animal_selected', ''))
    animal = Animal.objects.get(pk=selected)
    if request.method == 'POST':
        animal.delete()
        return HttpResponse("Animal removido com sucesso<br/><a href='animal'>Voltar</a>")



###############################################   Veterinario

def Cadastro_vet(request):
    if permissao(request):
        return render(request, 'polls/cadastro_vet.html', {"permissao": permissao(request)})
    else: return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")
    
     
def Salva_vet(request):
        if request.method == "POST":
            nome_vet = request.POST.get('nome', '')
            telefone = request.POST.get('telefone', )
            crv = request.POST.get('crv', '')
            endereco = request.POST.get('endereco', '')
            
            vet_obj = Veterinario(nome_vet=nome_vet, telefone=telefone,
            crv=crv, endereco=endereco)
            vet_obj.save()
            return HttpResponse("Veterinário cadastrado com sucesso<br/><a href='veterinario'>Voltar</a>")
        

def Edicao_vet(request):
    #chama a pag html com o form pra escolher qual animal editar
    if permissao(request):
        return render(request, 'polls/edicao_vet.html',
      {"vet": Veterinario.objects.all(), "permissao": permissao(request)})  #primeiro eu tenho q saber q vet editar
    else: 
        return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")

def form_update_vet(request):
    #chama o html para a edicao de um vet especifico
    selected = str(request.POST.get('vet_selected', ''))
    vet = Veterinario.objects.get(pk=selected)
    return render(request, 'polls/form_update_vet.html',  
    {'vet': vet})

def Update_vet(request):
    #atualiza o DB
    selected = str(request.POST.get('vet_selected', ''))
    animal = Veterinario.objects.get(pk=selected)

    nome = request.POST.get('nome', '')
    telefone = request.POST.get('telefone', )
    crv = request.POST.get('crv', '')
    endereco = request.POST.get('endereco', '')

    vet_obj = Veterinario(pk=selected,nome_vet=nome, 
                telefone=telefone, crv=crv, endereco=endereco)
    vet_obj.save()
    return HttpResponse("Veterinário editado com sucesso<br/><a href='veterinario'>Voltar</a>")
    

def Remocao_vet(request):
    if permissao(request):
        return render(request, 'polls/remocao_vet.html',
      {"vet": Veterinario.objects.all(), "permissao": permissao(request)})  #primeiro eu tenho q saber q vet remover
    else: return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")
def Remove_vet(request):
    #atualiza o DB
    selected = str(request.POST.get('vet_selected', ''))
    vet = Veterinario.objects.get(pk=selected)
    if request.method == 'POST':
        vet.delete()
        return HttpResponse("Veterinário removido com sucesso<br/><a href='veterinario'>Voltar</a>")




########################## Doacoes

###### Cadastro
def Cadastro_doacao(request):
    if permissao(request):
        return render(request, 'polls/cadastro_doacao.html', {"permissao": permissao(request)})
    else: return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")

     
def Salva_doacao(request):
        if request.method == "POST":
            nome = request.POST.get('nome', '')
            tel = request.POST.get('tel', )
            tipo = request.POST.get('tipo', '')
            qntidade = request.POST.get('qntidade', '')
            
            doacao_obj = Doacoes(nome_doador=nome, 
                tel_doador=tel, tipo_doacao=tipo, qntidade=qntidade)
            doacao_obj.save()
            return HttpResponse("Doacao cadastrada com sucesso<br/><a href='doacao'>Voltar</a>")


####### Edicao

def Edicao_doacao(request):
    #chama a pag html com o form pra escolher qual animal editar
    if permissao(request):
        return render(request, 'polls/edicao_doacao.html',
      {"doacao": Doacoes.objects.all(), "permissao": permissao(request)})  #primeiro eu tenho q saber q vet editar
    else: 
        return HttpResponse("Você precisa fazer <a href='../'>login</a> antes de acessar este conteúdo")

def form_update_doacao(request):
    #chama o html para a edicao de um vet especifico

ONG/polls/templates/polls/cadastro_animal.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Animal</title>
    </head>

    <body>
        <div class="conteudo">
        

        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        {% if permissao%}
        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal" class="current">Animais</a></p>
            <p><a href="veterinario">Veterinários</a></p>
            <p><a href="doacao">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Animal</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_animal' %}" class="current">Cadastro</a>  |
            <a href="{% url 'polls:edicao_animal' %}">Edição</a>  |
            <a href="{% url 'polls:remocao_animal' %}">Remoção</a>  
        </div>

        <form action="{% url 'polls:Salva_animal' %}" method="POST"> 
            {% csrf_token %} <!-- security seasons, whatever-->
            <p>
                <label>Nome: </label>
                <input type="text" name="nome" />
            </p>
            <p>
                <label>Idade:</label>
                <input type="number" name="idade" />
            </p>
            <p>
                <label>Especie:</label>
                <input type="text" name="especie" />
            </p>
            <p>
                <label>Raça:</label>
                <input type="text" name="raca" />
            </p>
            <p>
                <label>Observação:</label>
                <input type="text" name="observacao"/>
            </p>
    
            <br/>
            <label></label>
            <input type="submit" value="Cadastrar" /> 
        </form> 
        {% else %}
            Você precisa fazer <a href='login'>login</a> antes de visualizar este conteúdo.
        {% endif %}
        </div>  
    </body>
</html>

ONG/polls/templates/polls/cadastro_vet.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Veterinário</title>
    </head>

    <body>
        <div class="conteudo">
        
        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        {% if permissao %}
        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal">Animais</a></p>
            <p><a href="veterinario" class="current">Veterinários</a></p>
            <p><a href="doacao">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Veterinário</h2>
            <div class="menu">
                <a href="listagem">Listagem</a>  |
                <a href="{% url 'polls:cadastro_vet' %}" class="current">Cadastro</a>  |
                <a href="{% url 'polls:edicao_vet' %}">Edição</a>  |
                <a href="{% url 'polls:remocao_vet' %}">Remoção</a>  
            </div>

        <form action="{% url 'polls:Salva_vet' %}" method="POST"> 
            {% csrf_token %} <!-- security seasons, whatever-->
            <p>
                <label>Nome: </label>
                <input type="text" name="nome" />
            </p>
            <p>
                <label>Telefone:</label>
                <input type="number" name="telefone" />
            </p>
            <p>
                <label>CRV:</label>
                <input type="text" name="crv" />
            </p>
            <p>
                <label>Endereço:</label>
                <input type="text" name="endereco" />
            </p>
                
            <br/>
            <label></label>
            <input type="submit" value="Cadastrar" /> 
        </form> 
        {% else %}
            Você precisa fazer <a href='login'>login</a> antes de visualizar este conteúdo.
        {% endif %} 
        </div>  
    </body>
</html>

ONG/polls/templates/polls/edicao_animal.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Animal</title>
    </head>

    <body>
        <div class="conteudo">
        

        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        {% if permissao %}
        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal" class="current">Animais</a></p>
            <p><a href="veterinario">Veterinários</a></p>
            <p><a href="doacao">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Animal</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_animal' %}">Cadastro</a>  |
            <a href="{% url 'polls:edicao_animal' %}" class="current">Edição</a>  |
            <a href="{% url 'polls:remocao_animal' %}">Remoção</a>  
        </div>

        <br/>
        <form action="{% url 'polls:form_update_animal' %}" method="POST">
            {% csrf_token %} <!-- security seasons, dont ask Cross site request foreign-->
            <label>Editar:</label>
            <select name="animal_selected">
            {% for choice in animal %}
                    <option value="{{choice.pk}}">{{choice}}</option>            
                <br/>
            {% endfor %}
            </select>
            
            
            <input type="submit" value="Editar" /> 
        </form>
        {% else %}
            Você precisa fazer <a href='login'>login</a> antes de visualizar este conteúdo.
        {% endif %} 
        </div>  
    </body>
</html>

ONG/polls/templates/polls/edicao_doacao.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Doação</title>
    </head>

    <body>
        <div class="conteudo">
        

        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        {% if permissao %}
        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal">Animais</a></p>
            <p><a href="veterinario">Veterinários</a></p>
            <p><a href="doacao" class="current">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Doação</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_doacao' %}">Cadastro</a>  |
            <a href="{% url 'polls:edicao_doacao' %}" class="current">Edição</a>  | 
            <a href="{% url 'polls:remocao_doacao' %}">Remoção</a>
        </div>

        <br/>
        <form action="{% url 'polls:form_update_doacao' %}" method="POST">
            {% csrf_token %} <!-- security seasons, dont ask Cross site request foreign-->
            <label>Editar:</label>
            <select name="doacao_selected">
            {% for choice in doacao %}
                    <option value="{{choice.pk}}">{{choice}}</option>            
                <br/>
            {% endfor %}
            </select>
            
            
            <input type="submit" value="Editar" /> 
        </form> 
        {% else %}
            Você precisa fazer <a href='login'>login</a> antes de visualizar este conteúdo.
        {% endif %} 
        </div>  
    </body>
</html>

ONG/polls/templates/polls/edicao_vet.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Veterinário</title>
    </head>

    <body>
        <div class="conteudo">
        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        {% if permissao %}
        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal">Animais</a></p>
            <p><a href="veterinario" class="current">Veterinários</a></p>
            <p><a href="doacao">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Veterinário</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_vet' %}">Cadastro</a>  |
            <a href="{% url 'polls:edicao_vet' %}" class="current">Edição</a>  |
            <a href="{% url 'polls:remocao_vet' %}">Remoção</a>  
        </div>

        <br/>
        <form action="{% url 'polls:form_update_vet' %}" method="POST">
            {% csrf_token %} <!-- security seasons, dont ask Cross site request foreign-->
            <label>Editar:</label>
            <select name="vet_selected">
            {% for choice in vet %}
                    <option value="{{choice.pk}}">{{choice}}</option>            
                <br/>
            {% endfor %}
            </select>
            
            
            <input type="submit" value="Editar" /> 
        </form> 
        {% else %}
            Você precisa fazer <a href='login'>login</a> antes de visualizar este conteúdo.
        {% endif %} 
        </div>  
    </body>
</html>

ONG/polls/templates/polls/form_update_animal.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Animal</title>
    </head>

    <body>
        <div class="conteudo">
        

        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal" class="current">Animais</a></p>
            <p><a href="veterinario">Veterinários</a></p>
            <p><a href="doacao">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Animal</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_animal' %}">Cadastro</a>  |
            <a href="{% url 'polls:edicao_animal' %}" class="current">Edição</a>  |
            <a href="{% url 'polls:remocao_animal' %}">Remoção</a>  
        </div>

        <br/>
        <form action="{% url 'polls:update_animal' %}" method="POST">
            
            {% csrf_token %} <!-- security seasons, dont ask Cross site request foreign-->
            <input type="hidden" name="animal_selected" value="{{animal.pk}}" />
            <p>
                    <label>Nome: </label>
                    <input type="text" name="nome" value={{animal.nome_animal}}  />
                </p>
                <p>
                    <label>Idade:</label>
                    <input type="number" name="idade" value="{{animal.idade}}"  />
                </p>
                <p>
                    <label>Especie:</label>
                    <input type="text" name="especie" value="{{animal.especie}}"  />
                </p>
                <p>
                    <label>Raça:</label>
                    <input type="text" name="raca" value="{{animal.raca}}" />
                </p>
                <p>
                    <label>Observação:</label>
                    <input type="text" name="observacao" value="{{animal.observacao}}" />
                </p>
                <hr>
                <p>
                        <label>Nova Consulta:</label>
                        <input type="date" name="data"  />
                    </p>
    
                    <p>                
                        <label>Veterinário:</label>
                        <select name="vet_selected">
                        {% for choice in vet %}
                                <option value="{{choice.pk}}">{{choice}}</option>            
                            <br/>
                        {% endfor %}
                        </select>
                    </p>
                    <p>
                        <label>Observação:</label>
                        <input type="text" name="obs" />
                    </p>
            
            <label></label>
            <input type="submit" value="Editar" /> 
        </form> 
        </div>  
    </body>
</html>

ONG/polls/templates/polls/form_update_doacao.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Doação</title>
    </head>

    <body>
        <div class="conteudo">
        

        <header>
            <h1>ONG de Animais</h1>
            <hr>
        </header>

        <nav>
            <p><a href="../">Home Page</a></p>
            <p><a href="animal">Animais</a></p>
            <p><a href="veterinario">Veterinários</a></p>
            <p><a href="doacao" class="current">Doações</a></p>
        </nav>
        <div class="menu">
            <a href="logout">Logout</a> 
        </div>
        <h2>Doação</h2>
        <div class="menu">
            <a href="listagem">Listagem</a>  |
            <a href="{% url 'polls:cadastro_doacao' %}">Cadastro</a>  |
            <a href="{% url 'polls:edicao_doacao' %}" class="current">Edição</a>  |
            <a href="{% url 'polls:remocao_doacao' %}">Remoção</a>  
        </div>

        <br/>
        <form action="{% url 'polls:update_doacao' %}" method="POST">
            {% csrf_token %} <!-- security seasons, dont ask Cross site request foreign-->
            <input type="hidden" name="doacao_selected" value="{{doacao.pk}}" />
            <p>
                <label>Nome: </label>
                <input type="text" name="nome" id="doacao{{forloop.counter}}" value="{{doacao.nome_doador}}" />
            </p>
            <p>
                <label>Telefone:</label>
                <input type="number" name="tel" value="{{doacao.tel_doador}}" />
            </p>
            <p>
                <label>Tipo:</label>
                <select name="tipo">
                    <option value='racao'>Ração</option>
                    <option value='med'>Medicamentos</option>
                </select>
            </p>
            <p>
                <label>Quantidade:</label>
                <input type="number" name="qntidade" value="{{doacao.qntidade}}"/>
            </p>
            
            <label></label>
            <input type="submit" value="Editar" /> 
        </form> 
        </div>  
    </body>
</html>